name: comprenanto
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  get_it: ^8.0.3
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^9.2.2
  json_annotation: ^4.8.0
  firebase_analytics: ^11.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test_api: 0.7.3  # Pin to the version required by flutter_test
  # Add other dev dependencies as needed